export const maps = [
    {
        blank: [
            [
               {
                  "x":0,
                  "y":0,
                  "posX":0,
                  "posY":0,
                  "obstacle":false,
                  "id":"x0:y0"
               },
               {
                  "x":1,
                  "y":0,
                  "posX":50,
                  "posY":0,
                  "obstacle":false,
                  "id":"x1:y0"
               },
               {
                  "x":2,
                  "y":0,
                  "posX":100,
                  "posY":0,
                  "obstacle":false,
                  "id":"x2:y0"
               },
               {
                  "x":3,
                  "y":0,
                  "posX":150,
                  "posY":0,
                  "obstacle":false,
                  "id":"x3:y0"
               },
               {
                  "x":4,
                  "y":0,
                  "posX":200,
                  "posY":0,
                  "obstacle":false,
                  "id":"x4:y0"
               },
               {
                  "x":5,
                  "y":0,
                  "posX":250,
                  "posY":0,
                  "obstacle":false,
                  "id":"x5:y0"
               },
               {
                  "x":6,
                  "y":0,
                  "posX":300,
                  "posY":0,
                  "obstacle":false,
                  "id":"x6:y0"
               },
               {
                  "x":7,
                  "y":0,
                  "posX":350,
                  "posY":0,
                  "obstacle":false,
                  "id":"x7:y0"
               },
               {
                  "x":8,
                  "y":0,
                  "posX":400,
                  "posY":0,
                  "obstacle":false,
                  "id":"x8:y0"
               },
               {
                  "x":9,
                  "y":0,
                  "posX":450,
                  "posY":0,
                  "obstacle":false,
                  "id":"x9:y0"
               },
               {
                  "x":10,
                  "y":0,
                  "posX":500,
                  "posY":0,
                  "obstacle":false,
                  "id":"x10:y0"
               },
               {
                  "x":11,
                  "y":0,
                  "posX":550,
                  "posY":0,
                  "obstacle":false,
                  "id":"x11:y0"
               },
               {
                  "x":12,
                  "y":0,
                  "posX":600,
                  "posY":0,
                  "obstacle":false,
                  "id":"x12:y0"
               },
               {
                  "x":13,
                  "y":0,
                  "posX":650,
                  "posY":0,
                  "obstacle":false,
                  "id":"x13:y0"
               },
               {
                  "x":14,
                  "y":0,
                  "posX":700,
                  "posY":0,
                  "obstacle":false,
                  "id":"x14:y0"
               },
               {
                  "x":15,
                  "y":0,
                  "posX":750,
                  "posY":0,
                  "obstacle":false,
                  "id":"x15:y0"
               },
               {
                  "x":16,
                  "y":0,
                  "posX":800,
                  "posY":0,
                  "obstacle":false,
                  "id":"x16:y0"
               },
               {
                  "x":17,
                  "y":0,
                  "posX":850,
                  "posY":0,
                  "obstacle":false,
                  "id":"x17:y0"
               },
               {
                  "x":18,
                  "y":0,
                  "posX":900,
                  "posY":0,
                  "obstacle":false,
                  "id":"x18:y0"
               },
               {
                  "x":19,
                  "y":0,
                  "posX":950,
                  "posY":0,
                  "obstacle":false,
                  "id":"x19:y0"
               }
            ],
            [
               {
                  "x":0,
                  "y":1,
                  "posX":0,
                  "posY":50,
                  "obstacle":false,
                  "id":"x0:y1"
               },
               {
                  "x":1,
                  "y":1,
                  "posX":50,
                  "posY":50,
                  "obstacle":false,
                  "id":"x1:y1"
               },
               {
                  "x":2,
                  "y":1,
                  "posX":100,
                  "posY":50,
                  "obstacle":false,
                  "id":"x2:y1"
               },
               {
                  "x":3,
                  "y":1,
                  "posX":150,
                  "posY":50,
                  "obstacle":false,
                  "id":"x3:y1"
               },
               {
                  "x":4,
                  "y":1,
                  "posX":200,
                  "posY":50,
                  "obstacle":false,
                  "id":"x4:y1"
               },
               {
                  "x":5,
                  "y":1,
                  "posX":250,
                  "posY":50,
                  "obstacle":false,
                  "id":"x5:y1"
               },
               {
                  "x":6,
                  "y":1,
                  "posX":300,
                  "posY":50,
                  "obstacle":false,
                  "id":"x6:y1"
               },
               {
                  "x":7,
                  "y":1,
                  "posX":350,
                  "posY":50,
                  "obstacle":false,
                  "id":"x7:y1"
               },
               {
                  "x":8,
                  "y":1,
                  "posX":400,
                  "posY":50,
                  "obstacle":false,
                  "id":"x8:y1"
               },
               {
                  "x":9,
                  "y":1,
                  "posX":450,
                  "posY":50,
                  "obstacle":false,
                  "id":"x9:y1"
               },
               {
                  "x":10,
                  "y":1,
                  "posX":500,
                  "posY":50,
                  "obstacle":false,
                  "id":"x10:y1"
               },
               {
                  "x":11,
                  "y":1,
                  "posX":550,
                  "posY":50,
                  "obstacle":false,
                  "id":"x11:y1"
               },
               {
                  "x":12,
                  "y":1,
                  "posX":600,
                  "posY":50,
                  "obstacle":false,
                  "id":"x12:y1"
               },
               {
                  "x":13,
                  "y":1,
                  "posX":650,
                  "posY":50,
                  "obstacle":false,
                  "id":"x13:y1"
               },
               {
                  "x":14,
                  "y":1,
                  "posX":700,
                  "posY":50,
                  "obstacle":false,
                  "id":"x14:y1"
               },
               {
                  "x":15,
                  "y":1,
                  "posX":750,
                  "posY":50,
                  "obstacle":false,
                  "id":"x15:y1"
               },
               {
                  "x":16,
                  "y":1,
                  "posX":800,
                  "posY":50,
                  "obstacle":false,
                  "id":"x16:y1"
               },
               {
                  "x":17,
                  "y":1,
                  "posX":850,
                  "posY":50,
                  "obstacle":false,
                  "id":"x17:y1"
               },
               {
                  "x":18,
                  "y":1,
                  "posX":900,
                  "posY":50,
                  "obstacle":false,
                  "id":"x18:y1"
               },
               {
                  "x":19,
                  "y":1,
                  "posX":950,
                  "posY":50,
                  "obstacle":false,
                  "id":"x19:y1"
               }
            ],
            [
               {
                  "x":0,
                  "y":2,
                  "posX":0,
                  "posY":100,
                  "obstacle":false,
                  "id":"x0:y2"
               },
               {
                  "x":1,
                  "y":2,
                  "posX":50,
                  "posY":100,
                  "obstacle":false,
                  "id":"x1:y2"
               },
               {
                  "x":2,
                  "y":2,
                  "posX":100,
                  "posY":100,
                  "obstacle":false,
                  "id":"x2:y2"
               },
               {
                  "x":3,
                  "y":2,
                  "posX":150,
                  "posY":100,
                  "obstacle":false,
                  "id":"x3:y2"
               },
               {
                  "x":4,
                  "y":2,
                  "posX":200,
                  "posY":100,
                  "obstacle":false,
                  "id":"x4:y2"
               },
               {
                  "x":5,
                  "y":2,
                  "posX":250,
                  "posY":100,
                  "obstacle":false,
                  "id":"x5:y2"
               },
               {
                  "x":6,
                  "y":2,
                  "posX":300,
                  "posY":100,
                  "obstacle":false,
                  "id":"x6:y2"
               },
               {
                  "x":7,
                  "y":2,
                  "posX":350,
                  "posY":100,
                  "obstacle":false,
                  "id":"x7:y2"
               },
               {
                  "x":8,
                  "y":2,
                  "posX":400,
                  "posY":100,
                  "obstacle":false,
                  "id":"x8:y2"
               },
               {
                  "x":9,
                  "y":2,
                  "posX":450,
                  "posY":100,
                  "obstacle":false,
                  "id":"x9:y2"
               },
               {
                  "x":10,
                  "y":2,
                  "posX":500,
                  "posY":100,
                  "obstacle":false,
                  "id":"x10:y2"
               },
               {
                  "x":11,
                  "y":2,
                  "posX":550,
                  "posY":100,
                  "obstacle":false,
                  "id":"x11:y2"
               },
               {
                  "x":12,
                  "y":2,
                  "posX":600,
                  "posY":100,
                  "obstacle":false,
                  "id":"x12:y2"
               },
               {
                  "x":13,
                  "y":2,
                  "posX":650,
                  "posY":100,
                  "obstacle":false,
                  "id":"x13:y2"
               },
               {
                  "x":14,
                  "y":2,
                  "posX":700,
                  "posY":100,
                  "obstacle":false,
                  "id":"x14:y2"
               },
               {
                  "x":15,
                  "y":2,
                  "posX":750,
                  "posY":100,
                  "obstacle":false,
                  "id":"x15:y2"
               },
               {
                  "x":16,
                  "y":2,
                  "posX":800,
                  "posY":100,
                  "obstacle":false,
                  "id":"x16:y2"
               },
               {
                  "x":17,
                  "y":2,
                  "posX":850,
                  "posY":100,
                  "obstacle":false,
                  "id":"x17:y2"
               },
               {
                  "x":18,
                  "y":2,
                  "posX":900,
                  "posY":100,
                  "obstacle":false,
                  "id":"x18:y2"
               },
               {
                  "x":19,
                  "y":2,
                  "posX":950,
                  "posY":100,
                  "obstacle":false,
                  "id":"x19:y2"
               }
            ],
            [
               {
                  "x":0,
                  "y":3,
                  "posX":0,
                  "posY":150,
                  "obstacle":false,
                  "id":"x0:y3"
               },
               {
                  "x":1,
                  "y":3,
                  "posX":50,
                  "posY":150,
                  "obstacle":false,
                  "id":"x1:y3"
               },
               {
                  "x":2,
                  "y":3,
                  "posX":100,
                  "posY":150,
                  "obstacle":false,
                  "id":"x2:y3"
               },
               {
                  "x":3,
                  "y":3,
                  "posX":150,
                  "posY":150,
                  "obstacle":false,
                  "id":"x3:y3"
               },
               {
                  "x":4,
                  "y":3,
                  "posX":200,
                  "posY":150,
                  "obstacle":false,
                  "id":"x4:y3"
               },
               {
                  "x":5,
                  "y":3,
                  "posX":250,
                  "posY":150,
                  "obstacle":false,
                  "id":"x5:y3"
               },
               {
                  "x":6,
                  "y":3,
                  "posX":300,
                  "posY":150,
                  "obstacle":false,
                  "id":"x6:y3"
               },
               {
                  "x":7,
                  "y":3,
                  "posX":350,
                  "posY":150,
                  "obstacle":false,
                  "id":"x7:y3"
               },
               {
                  "x":8,
                  "y":3,
                  "posX":400,
                  "posY":150,
                  "obstacle":false,
                  "id":"x8:y3"
               },
               {
                  "x":9,
                  "y":3,
                  "posX":450,
                  "posY":150,
                  "obstacle":false,
                  "id":"x9:y3"
               },
               {
                  "x":10,
                  "y":3,
                  "posX":500,
                  "posY":150,
                  "obstacle":false,
                  "id":"x10:y3"
               },
               {
                  "x":11,
                  "y":3,
                  "posX":550,
                  "posY":150,
                  "obstacle":false,
                  "id":"x11:y3"
               },
               {
                  "x":12,
                  "y":3,
                  "posX":600,
                  "posY":150,
                  "obstacle":false,
                  "id":"x12:y3"
               },
               {
                  "x":13,
                  "y":3,
                  "posX":650,
                  "posY":150,
                  "obstacle":false,
                  "id":"x13:y3"
               },
               {
                  "x":14,
                  "y":3,
                  "posX":700,
                  "posY":150,
                  "obstacle":false,
                  "id":"x14:y3"
               },
               {
                  "x":15,
                  "y":3,
                  "posX":750,
                  "posY":150,
                  "obstacle":false,
                  "id":"x15:y3"
               },
               {
                  "x":16,
                  "y":3,
                  "posX":800,
                  "posY":150,
                  "obstacle":false,
                  "id":"x16:y3"
               },
               {
                  "x":17,
                  "y":3,
                  "posX":850,
                  "posY":150,
                  "obstacle":false,
                  "id":"x17:y3"
               },
               {
                  "x":18,
                  "y":3,
                  "posX":900,
                  "posY":150,
                  "obstacle":false,
                  "id":"x18:y3"
               },
               {
                  "x":19,
                  "y":3,
                  "posX":950,
                  "posY":150,
                  "obstacle":false,
                  "id":"x19:y3"
               }
            ],
            [
               {
                  "x":0,
                  "y":4,
                  "posX":0,
                  "posY":200,
                  "obstacle":false,
                  "id":"x0:y4"
               },
               {
                  "x":1,
                  "y":4,
                  "posX":50,
                  "posY":200,
                  "obstacle":false,
                  "id":"x1:y4"
               },
               {
                  "x":2,
                  "y":4,
                  "posX":100,
                  "posY":200,
                  "obstacle":false,
                  "id":"x2:y4"
               },
               {
                  "x":3,
                  "y":4,
                  "posX":150,
                  "posY":200,
                  "obstacle":false,
                  "id":"x3:y4"
               },
               {
                  "x":4,
                  "y":4,
                  "posX":200,
                  "posY":200,
                  "obstacle":false,
                  "id":"x4:y4"
               },
               {
                  "x":5,
                  "y":4,
                  "posX":250,
                  "posY":200,
                  "obstacle":false,
                  "id":"x5:y4"
               },
               {
                  "x":6,
                  "y":4,
                  "posX":300,
                  "posY":200,
                  "obstacle":false,
                  "id":"x6:y4"
               },
               {
                  "x":7,
                  "y":4,
                  "posX":350,
                  "posY":200,
                  "obstacle":false,
                  "id":"x7:y4"
               },
               {
                  "x":8,
                  "y":4,
                  "posX":400,
                  "posY":200,
                  "obstacle":false,
                  "id":"x8:y4"
               },
               {
                  "x":9,
                  "y":4,
                  "posX":450,
                  "posY":200,
                  "obstacle":false,
                  "id":"x9:y4"
               },
               {
                  "x":10,
                  "y":4,
                  "posX":500,
                  "posY":200,
                  "obstacle":false,
                  "id":"x10:y4"
               },
               {
                  "x":11,
                  "y":4,
                  "posX":550,
                  "posY":200,
                  "obstacle":false,
                  "id":"x11:y4"
               },
               {
                  "x":12,
                  "y":4,
                  "posX":600,
                  "posY":200,
                  "obstacle":false,
                  "id":"x12:y4"
               },
               {
                  "x":13,
                  "y":4,
                  "posX":650,
                  "posY":200,
                  "obstacle":false,
                  "id":"x13:y4"
               },
               {
                  "x":14,
                  "y":4,
                  "posX":700,
                  "posY":200,
                  "obstacle":false,
                  "id":"x14:y4"
               },
               {
                  "x":15,
                  "y":4,
                  "posX":750,
                  "posY":200,
                  "obstacle":false,
                  "id":"x15:y4"
               },
               {
                  "x":16,
                  "y":4,
                  "posX":800,
                  "posY":200,
                  "obstacle":false,
                  "id":"x16:y4"
               },
               {
                  "x":17,
                  "y":4,
                  "posX":850,
                  "posY":200,
                  "obstacle":false,
                  "id":"x17:y4"
               },
               {
                  "x":18,
                  "y":4,
                  "posX":900,
                  "posY":200,
                  "obstacle":false,
                  "id":"x18:y4"
               },
               {
                  "x":19,
                  "y":4,
                  "posX":950,
                  "posY":200,
                  "obstacle":false,
                  "id":"x19:y4"
               }
            ],
            [
               {
                  "x":0,
                  "y":5,
                  "posX":0,
                  "posY":250,
                  "obstacle":false,
                  "id":"x0:y5"
               },
               {
                  "x":1,
                  "y":5,
                  "posX":50,
                  "posY":250,
                  "obstacle":false,
                  "id":"x1:y5"
               },
               {
                  "x":2,
                  "y":5,
                  "posX":100,
                  "posY":250,
                  "obstacle":false,
                  "id":"x2:y5"
               },
               {
                  "x":3,
                  "y":5,
                  "posX":150,
                  "posY":250,
                  "obstacle":false,
                  "id":"x3:y5"
               },
               {
                  "x":4,
                  "y":5,
                  "posX":200,
                  "posY":250,
                  "obstacle":false,
                  "id":"x4:y5"
               },
               {
                  "x":5,
                  "y":5,
                  "posX":250,
                  "posY":250,
                  "obstacle":false,
                  "id":"x5:y5"
               },
               {
                  "x":6,
                  "y":5,
                  "posX":300,
                  "posY":250,
                  "obstacle":false,
                  "id":"x6:y5"
               },
               {
                  "x":7,
                  "y":5,
                  "posX":350,
                  "posY":250,
                  "obstacle":false,
                  "id":"x7:y5"
               },
               {
                  "x":8,
                  "y":5,
                  "posX":400,
                  "posY":250,
                  "obstacle":false,
                  "id":"x8:y5"
               },
               {
                  "x":9,
                  "y":5,
                  "posX":450,
                  "posY":250,
                  "obstacle":false,
                  "id":"x9:y5"
               },
               {
                  "x":10,
                  "y":5,
                  "posX":500,
                  "posY":250,
                  "obstacle":false,
                  "id":"x10:y5"
               },
               {
                  "x":11,
                  "y":5,
                  "posX":550,
                  "posY":250,
                  "obstacle":false,
                  "id":"x11:y5"
               },
               {
                  "x":12,
                  "y":5,
                  "posX":600,
                  "posY":250,
                  "obstacle":false,
                  "id":"x12:y5"
               },
               {
                  "x":13,
                  "y":5,
                  "posX":650,
                  "posY":250,
                  "obstacle":false,
                  "id":"x13:y5"
               },
               {
                  "x":14,
                  "y":5,
                  "posX":700,
                  "posY":250,
                  "obstacle":false,
                  "id":"x14:y5"
               },
               {
                  "x":15,
                  "y":5,
                  "posX":750,
                  "posY":250,
                  "obstacle":false,
                  "id":"x15:y5"
               },
               {
                  "x":16,
                  "y":5,
                  "posX":800,
                  "posY":250,
                  "obstacle":false,
                  "id":"x16:y5"
               },
               {
                  "x":17,
                  "y":5,
                  "posX":850,
                  "posY":250,
                  "obstacle":false,
                  "id":"x17:y5"
               },
               {
                  "x":18,
                  "y":5,
                  "posX":900,
                  "posY":250,
                  "obstacle":false,
                  "id":"x18:y5"
               },
               {
                  "x":19,
                  "y":5,
                  "posX":950,
                  "posY":250,
                  "obstacle":false,
                  "id":"x19:y5"
               }
            ],
            [
               {
                  "x":0,
                  "y":6,
                  "posX":0,
                  "posY":300,
                  "obstacle":false,
                  "id":"x0:y6"
               },
               {
                  "x":1,
                  "y":6,
                  "posX":50,
                  "posY":300,
                  "obstacle":false,
                  "id":"x1:y6"
               },
               {
                  "x":2,
                  "y":6,
                  "posX":100,
                  "posY":300,
                  "obstacle":false,
                  "id":"x2:y6"
               },
               {
                  "x":3,
                  "y":6,
                  "posX":150,
                  "posY":300,
                  "obstacle":false,
                  "id":"x3:y6"
               },
               {
                  "x":4,
                  "y":6,
                  "posX":200,
                  "posY":300,
                  "obstacle":false,
                  "id":"x4:y6"
               },
               {
                  "x":5,
                  "y":6,
                  "posX":250,
                  "posY":300,
                  "obstacle":false,
                  "id":"x5:y6"
               },
               {
                  "x":6,
                  "y":6,
                  "posX":300,
                  "posY":300,
                  "obstacle":false,
                  "id":"x6:y6"
               },
               {
                  "x":7,
                  "y":6,
                  "posX":350,
                  "posY":300,
                  "obstacle":false,
                  "id":"x7:y6"
               },
               {
                  "x":8,
                  "y":6,
                  "posX":400,
                  "posY":300,
                  "obstacle":false,
                  "id":"x8:y6"
               },
               {
                  "x":9,
                  "y":6,
                  "posX":450,
                  "posY":300,
                  "obstacle":false,
                  "id":"x9:y6"
               },
               {
                  "x":10,
                  "y":6,
                  "posX":500,
                  "posY":300,
                  "obstacle":false,
                  "id":"x10:y6"
               },
               {
                  "x":11,
                  "y":6,
                  "posX":550,
                  "posY":300,
                  "obstacle":false,
                  "id":"x11:y6"
               },
               {
                  "x":12,
                  "y":6,
                  "posX":600,
                  "posY":300,
                  "obstacle":false,
                  "id":"x12:y6"
               },
               {
                  "x":13,
                  "y":6,
                  "posX":650,
                  "posY":300,
                  "obstacle":false,
                  "id":"x13:y6"
               },
               {
                  "x":14,
                  "y":6,
                  "posX":700,
                  "posY":300,
                  "obstacle":false,
                  "id":"x14:y6"
               },
               {
                  "x":15,
                  "y":6,
                  "posX":750,
                  "posY":300,
                  "obstacle":false,
                  "id":"x15:y6"
               },
               {
                  "x":16,
                  "y":6,
                  "posX":800,
                  "posY":300,
                  "obstacle":false,
                  "id":"x16:y6"
               },
               {
                  "x":17,
                  "y":6,
                  "posX":850,
                  "posY":300,
                  "obstacle":false,
                  "id":"x17:y6"
               },
               {
                  "x":18,
                  "y":6,
                  "posX":900,
                  "posY":300,
                  "obstacle":false,
                  "id":"x18:y6"
               },
               {
                  "x":19,
                  "y":6,
                  "posX":950,
                  "posY":300,
                  "obstacle":false,
                  "id":"x19:y6"
               }
            ],
            [
               {
                  "x":0,
                  "y":7,
                  "posX":0,
                  "posY":350,
                  "obstacle":false,
                  "id":"x0:y7"
               },
               {
                  "x":1,
                  "y":7,
                  "posX":50,
                  "posY":350,
                  "obstacle":false,
                  "id":"x1:y7"
               },
               {
                  "x":2,
                  "y":7,
                  "posX":100,
                  "posY":350,
                  "obstacle":false,
                  "id":"x2:y7"
               },
               {
                  "x":3,
                  "y":7,
                  "posX":150,
                  "posY":350,
                  "obstacle":false,
                  "id":"x3:y7"
               },
               {
                  "x":4,
                  "y":7,
                  "posX":200,
                  "posY":350,
                  "obstacle":false,
                  "id":"x4:y7"
               },
               {
                  "x":5,
                  "y":7,
                  "posX":250,
                  "posY":350,
                  "obstacle":false,
                  "id":"x5:y7"
               },
               {
                  "x":6,
                  "y":7,
                  "posX":300,
                  "posY":350,
                  "obstacle":false,
                  "id":"x6:y7"
               },
               {
                  "x":7,
                  "y":7,
                  "posX":350,
                  "posY":350,
                  "obstacle":false,
                  "id":"x7:y7"
               },
               {
                  "x":8,
                  "y":7,
                  "posX":400,
                  "posY":350,
                  "obstacle":false,
                  "id":"x8:y7"
               },
               {
                  "x":9,
                  "y":7,
                  "posX":450,
                  "posY":350,
                  "obstacle":false,
                  "id":"x9:y7"
               },
               {
                  "x":10,
                  "y":7,
                  "posX":500,
                  "posY":350,
                  "obstacle":false,
                  "id":"x10:y7"
               },
               {
                  "x":11,
                  "y":7,
                  "posX":550,
                  "posY":350,
                  "obstacle":false,
                  "id":"x11:y7"
               },
               {
                  "x":12,
                  "y":7,
                  "posX":600,
                  "posY":350,
                  "obstacle":false,
                  "id":"x12:y7"
               },
               {
                  "x":13,
                  "y":7,
                  "posX":650,
                  "posY":350,
                  "obstacle":false,
                  "id":"x13:y7"
               },
               {
                  "x":14,
                  "y":7,
                  "posX":700,
                  "posY":350,
                  "obstacle":false,
                  "id":"x14:y7"
               },
               {
                  "x":15,
                  "y":7,
                  "posX":750,
                  "posY":350,
                  "obstacle":false,
                  "id":"x15:y7"
               },
               {
                  "x":16,
                  "y":7,
                  "posX":800,
                  "posY":350,
                  "obstacle":false,
                  "id":"x16:y7"
               },
               {
                  "x":17,
                  "y":7,
                  "posX":850,
                  "posY":350,
                  "obstacle":false,
                  "id":"x17:y7"
               },
               {
                  "x":18,
                  "y":7,
                  "posX":900,
                  "posY":350,
                  "obstacle":false,
                  "id":"x18:y7"
               },
               {
                  "x":19,
                  "y":7,
                  "posX":950,
                  "posY":350,
                  "obstacle":false,
                  "id":"x19:y7"
               }
            ],
            [
               {
                  "x":0,
                  "y":8,
                  "posX":0,
                  "posY":400,
                  "obstacle":false,
                  "id":"x0:y8"
               },
               {
                  "x":1,
                  "y":8,
                  "posX":50,
                  "posY":400,
                  "obstacle":false,
                  "id":"x1:y8"
               },
               {
                  "x":2,
                  "y":8,
                  "posX":100,
                  "posY":400,
                  "obstacle":false,
                  "id":"x2:y8"
               },
               {
                  "x":3,
                  "y":8,
                  "posX":150,
                  "posY":400,
                  "obstacle":false,
                  "id":"x3:y8"
               },
               {
                  "x":4,
                  "y":8,
                  "posX":200,
                  "posY":400,
                  "obstacle":false,
                  "id":"x4:y8"
               },
               {
                  "x":5,
                  "y":8,
                  "posX":250,
                  "posY":400,
                  "obstacle":false,
                  "id":"x5:y8"
               },
               {
                  "x":6,
                  "y":8,
                  "posX":300,
                  "posY":400,
                  "obstacle":false,
                  "id":"x6:y8"
               },
               {
                  "x":7,
                  "y":8,
                  "posX":350,
                  "posY":400,
                  "obstacle":false,
                  "id":"x7:y8"
               },
               {
                  "x":8,
                  "y":8,
                  "posX":400,
                  "posY":400,
                  "obstacle":false,
                  "id":"x8:y8"
               },
               {
                  "x":9,
                  "y":8,
                  "posX":450,
                  "posY":400,
                  "obstacle":false,
                  "id":"x9:y8"
               },
               {
                  "x":10,
                  "y":8,
                  "posX":500,
                  "posY":400,
                  "obstacle":false,
                  "id":"x10:y8"
               },
               {
                  "x":11,
                  "y":8,
                  "posX":550,
                  "posY":400,
                  "obstacle":false,
                  "id":"x11:y8"
               },
               {
                  "x":12,
                  "y":8,
                  "posX":600,
                  "posY":400,
                  "obstacle":false,
                  "id":"x12:y8"
               },
               {
                  "x":13,
                  "y":8,
                  "posX":650,
                  "posY":400,
                  "obstacle":false,
                  "id":"x13:y8"
               },
               {
                  "x":14,
                  "y":8,
                  "posX":700,
                  "posY":400,
                  "obstacle":false,
                  "id":"x14:y8"
               },
               {
                  "x":15,
                  "y":8,
                  "posX":750,
                  "posY":400,
                  "obstacle":false,
                  "id":"x15:y8"
               },
               {
                  "x":16,
                  "y":8,
                  "posX":800,
                  "posY":400,
                  "obstacle":false,
                  "id":"x16:y8"
               },
               {
                  "x":17,
                  "y":8,
                  "posX":850,
                  "posY":400,
                  "obstacle":false,
                  "id":"x17:y8"
               },
               {
                  "x":18,
                  "y":8,
                  "posX":900,
                  "posY":400,
                  "obstacle":false,
                  "id":"x18:y8"
               },
               {
                  "x":19,
                  "y":8,
                  "posX":950,
                  "posY":400,
                  "obstacle":false,
                  "id":"x19:y8"
               }
            ],
            [
               {
                  "x":0,
                  "y":9,
                  "posX":0,
                  "posY":450,
                  "obstacle":false,
                  "id":"x0:y9"
               },
               {
                  "x":1,
                  "y":9,
                  "posX":50,
                  "posY":450,
                  "obstacle":false,
                  "id":"x1:y9"
               },
               {
                  "x":2,
                  "y":9,
                  "posX":100,
                  "posY":450,
                  "obstacle":false,
                  "id":"x2:y9"
               },
               {
                  "x":3,
                  "y":9,
                  "posX":150,
                  "posY":450,
                  "obstacle":false,
                  "id":"x3:y9"
               },
               {
                  "x":4,
                  "y":9,
                  "posX":200,
                  "posY":450,
                  "obstacle":false,
                  "id":"x4:y9"
               },
               {
                  "x":5,
                  "y":9,
                  "posX":250,
                  "posY":450,
                  "obstacle":false,
                  "id":"x5:y9"
               },
               {
                  "x":6,
                  "y":9,
                  "posX":300,
                  "posY":450,
                  "obstacle":false,
                  "id":"x6:y9"
               },
               {
                  "x":7,
                  "y":9,
                  "posX":350,
                  "posY":450,
                  "obstacle":false,
                  "id":"x7:y9"
               },
               {
                  "x":8,
                  "y":9,
                  "posX":400,
                  "posY":450,
                  "obstacle":false,
                  "id":"x8:y9"
               },
               {
                  "x":9,
                  "y":9,
                  "posX":450,
                  "posY":450,
                  "obstacle":false,
                  "id":"x9:y9"
               },
               {
                  "x":10,
                  "y":9,
                  "posX":500,
                  "posY":450,
                  "obstacle":false,
                  "id":"x10:y9"
               },
               {
                  "x":11,
                  "y":9,
                  "posX":550,
                  "posY":450,
                  "obstacle":false,
                  "id":"x11:y9"
               },
               {
                  "x":12,
                  "y":9,
                  "posX":600,
                  "posY":450,
                  "obstacle":false,
                  "id":"x12:y9"
               },
               {
                  "x":13,
                  "y":9,
                  "posX":650,
                  "posY":450,
                  "obstacle":false,
                  "id":"x13:y9"
               },
               {
                  "x":14,
                  "y":9,
                  "posX":700,
                  "posY":450,
                  "obstacle":false,
                  "id":"x14:y9"
               },
               {
                  "x":15,
                  "y":9,
                  "posX":750,
                  "posY":450,
                  "obstacle":false,
                  "id":"x15:y9"
               },
               {
                  "x":16,
                  "y":9,
                  "posX":800,
                  "posY":450,
                  "obstacle":false,
                  "id":"x16:y9"
               },
               {
                  "x":17,
                  "y":9,
                  "posX":850,
                  "posY":450,
                  "obstacle":false,
                  "id":"x17:y9"
               },
               {
                  "x":18,
                  "y":9,
                  "posX":900,
                  "posY":450,
                  "obstacle":false,
                  "id":"x18:y9"
               },
               {
                  "x":19,
                  "y":9,
                  "posX":950,
                  "posY":450,
                  "obstacle":false,
                  "id":"x19:y9"
               }
            ],
            [
               {
                  "x":0,
                  "y":10,
                  "posX":0,
                  "posY":500,
                  "obstacle":false,
                  "id":"x0:y10"
               },
               {
                  "x":1,
                  "y":10,
                  "posX":50,
                  "posY":500,
                  "obstacle":false,
                  "id":"x1:y10"
               },
               {
                  "x":2,
                  "y":10,
                  "posX":100,
                  "posY":500,
                  "obstacle":false,
                  "id":"x2:y10"
               },
               {
                  "x":3,
                  "y":10,
                  "posX":150,
                  "posY":500,
                  "obstacle":false,
                  "id":"x3:y10"
               },
               {
                  "x":4,
                  "y":10,
                  "posX":200,
                  "posY":500,
                  "obstacle":false,
                  "id":"x4:y10"
               },
               {
                  "x":5,
                  "y":10,
                  "posX":250,
                  "posY":500,
                  "obstacle":false,
                  "id":"x5:y10"
               },
               {
                  "x":6,
                  "y":10,
                  "posX":300,
                  "posY":500,
                  "obstacle":false,
                  "id":"x6:y10"
               },
               {
                  "x":7,
                  "y":10,
                  "posX":350,
                  "posY":500,
                  "obstacle":false,
                  "id":"x7:y10"
               },
               {
                  "x":8,
                  "y":10,
                  "posX":400,
                  "posY":500,
                  "obstacle":false,
                  "id":"x8:y10"
               },
               {
                  "x":9,
                  "y":10,
                  "posX":450,
                  "posY":500,
                  "obstacle":false,
                  "id":"x9:y10"
               },
               {
                  "x":10,
                  "y":10,
                  "posX":500,
                  "posY":500,
                  "obstacle":false,
                  "id":"x10:y10"
               },
               {
                  "x":11,
                  "y":10,
                  "posX":550,
                  "posY":500,
                  "obstacle":false,
                  "id":"x11:y10"
               },
               {
                  "x":12,
                  "y":10,
                  "posX":600,
                  "posY":500,
                  "obstacle":false,
                  "id":"x12:y10"
               },
               {
                  "x":13,
                  "y":10,
                  "posX":650,
                  "posY":500,
                  "obstacle":false,
                  "id":"x13:y10"
               },
               {
                  "x":14,
                  "y":10,
                  "posX":700,
                  "posY":500,
                  "obstacle":false,
                  "id":"x14:y10"
               },
               {
                  "x":15,
                  "y":10,
                  "posX":750,
                  "posY":500,
                  "obstacle":false,
                  "id":"x15:y10"
               },
               {
                  "x":16,
                  "y":10,
                  "posX":800,
                  "posY":500,
                  "obstacle":false,
                  "id":"x16:y10"
               },
               {
                  "x":17,
                  "y":10,
                  "posX":850,
                  "posY":500,
                  "obstacle":false,
                  "id":"x17:y10"
               },
               {
                  "x":18,
                  "y":10,
                  "posX":900,
                  "posY":500,
                  "obstacle":false,
                  "id":"x18:y10"
               },
               {
                  "x":19,
                  "y":10,
                  "posX":950,
                  "posY":500,
                  "obstacle":false,
                  "id":"x19:y10"
               }
            ],
            [
               {
                  "x":0,
                  "y":11,
                  "posX":0,
                  "posY":550,
                  "obstacle":false,
                  "id":"x0:y11"
               },
               {
                  "x":1,
                  "y":11,
                  "posX":50,
                  "posY":550,
                  "obstacle":false,
                  "id":"x1:y11"
               },
               {
                  "x":2,
                  "y":11,
                  "posX":100,
                  "posY":550,
                  "obstacle":false,
                  "id":"x2:y11"
               },
               {
                  "x":3,
                  "y":11,
                  "posX":150,
                  "posY":550,
                  "obstacle":false,
                  "id":"x3:y11"
               },
               {
                  "x":4,
                  "y":11,
                  "posX":200,
                  "posY":550,
                  "obstacle":false,
                  "id":"x4:y11"
               },
               {
                  "x":5,
                  "y":11,
                  "posX":250,
                  "posY":550,
                  "obstacle":false,
                  "id":"x5:y11"
               },
               {
                  "x":6,
                  "y":11,
                  "posX":300,
                  "posY":550,
                  "obstacle":false,
                  "id":"x6:y11"
               },
               {
                  "x":7,
                  "y":11,
                  "posX":350,
                  "posY":550,
                  "obstacle":false,
                  "id":"x7:y11"
               },
               {
                  "x":8,
                  "y":11,
                  "posX":400,
                  "posY":550,
                  "obstacle":false,
                  "id":"x8:y11"
               },
               {
                  "x":9,
                  "y":11,
                  "posX":450,
                  "posY":550,
                  "obstacle":false,
                  "id":"x9:y11"
               },
               {
                  "x":10,
                  "y":11,
                  "posX":500,
                  "posY":550,
                  "obstacle":false,
                  "id":"x10:y11"
               },
               {
                  "x":11,
                  "y":11,
                  "posX":550,
                  "posY":550,
                  "obstacle":false,
                  "id":"x11:y11"
               },
               {
                  "x":12,
                  "y":11,
                  "posX":600,
                  "posY":550,
                  "obstacle":false,
                  "id":"x12:y11"
               },
               {
                  "x":13,
                  "y":11,
                  "posX":650,
                  "posY":550,
                  "obstacle":false,
                  "id":"x13:y11"
               },
               {
                  "x":14,
                  "y":11,
                  "posX":700,
                  "posY":550,
                  "obstacle":false,
                  "id":"x14:y11"
               },
               {
                  "x":15,
                  "y":11,
                  "posX":750,
                  "posY":550,
                  "obstacle":false,
                  "id":"x15:y11"
               },
               {
                  "x":16,
                  "y":11,
                  "posX":800,
                  "posY":550,
                  "obstacle":false,
                  "id":"x16:y11"
               },
               {
                  "x":17,
                  "y":11,
                  "posX":850,
                  "posY":550,
                  "obstacle":false,
                  "id":"x17:y11"
               },
               {
                  "x":18,
                  "y":11,
                  "posX":900,
                  "posY":550,
                  "obstacle":false,
                  "id":"x18:y11"
               },
               {
                  "x":19,
                  "y":11,
                  "posX":950,
                  "posY":550,
                  "obstacle":false,
                  "id":"x19:y11"
               }
            ],
            [
               {
                  "x":0,
                  "y":12,
                  "posX":0,
                  "posY":600,
                  "obstacle":false,
                  "id":"x0:y12"
               },
               {
                  "x":1,
                  "y":12,
                  "posX":50,
                  "posY":600,
                  "obstacle":false,
                  "id":"x1:y12"
               },
               {
                  "x":2,
                  "y":12,
                  "posX":100,
                  "posY":600,
                  "obstacle":false,
                  "id":"x2:y12"
               },
               {
                  "x":3,
                  "y":12,
                  "posX":150,
                  "posY":600,
                  "obstacle":false,
                  "id":"x3:y12"
               },
               {
                  "x":4,
                  "y":12,
                  "posX":200,
                  "posY":600,
                  "obstacle":false,
                  "id":"x4:y12"
               },
               {
                  "x":5,
                  "y":12,
                  "posX":250,
                  "posY":600,
                  "obstacle":false,
                  "id":"x5:y12"
               },
               {
                  "x":6,
                  "y":12,
                  "posX":300,
                  "posY":600,
                  "obstacle":false,
                  "id":"x6:y12"
               },
               {
                  "x":7,
                  "y":12,
                  "posX":350,
                  "posY":600,
                  "obstacle":false,
                  "id":"x7:y12"
               },
               {
                  "x":8,
                  "y":12,
                  "posX":400,
                  "posY":600,
                  "obstacle":false,
                  "id":"x8:y12"
               },
               {
                  "x":9,
                  "y":12,
                  "posX":450,
                  "posY":600,
                  "obstacle":false,
                  "id":"x9:y12"
               },
               {
                  "x":10,
                  "y":12,
                  "posX":500,
                  "posY":600,
                  "obstacle":false,
                  "id":"x10:y12"
               },
               {
                  "x":11,
                  "y":12,
                  "posX":550,
                  "posY":600,
                  "obstacle":false,
                  "id":"x11:y12"
               },
               {
                  "x":12,
                  "y":12,
                  "posX":600,
                  "posY":600,
                  "obstacle":false,
                  "id":"x12:y12"
               },
               {
                  "x":13,
                  "y":12,
                  "posX":650,
                  "posY":600,
                  "obstacle":false,
                  "id":"x13:y12"
               },
               {
                  "x":14,
                  "y":12,
                  "posX":700,
                  "posY":600,
                  "obstacle":false,
                  "id":"x14:y12"
               },
               {
                  "x":15,
                  "y":12,
                  "posX":750,
                  "posY":600,
                  "obstacle":false,
                  "id":"x15:y12"
               },
               {
                  "x":16,
                  "y":12,
                  "posX":800,
                  "posY":600,
                  "obstacle":false,
                  "id":"x16:y12"
               },
               {
                  "x":17,
                  "y":12,
                  "posX":850,
                  "posY":600,
                  "obstacle":false,
                  "id":"x17:y12"
               },
               {
                  "x":18,
                  "y":12,
                  "posX":900,
                  "posY":600,
                  "obstacle":false,
                  "id":"x18:y12"
               },
               {
                  "x":19,
                  "y":12,
                  "posX":950,
                  "posY":600,
                  "obstacle":false,
                  "id":"x19:y12"
               }
            ],
            [
               {
                  "x":0,
                  "y":13,
                  "posX":0,
                  "posY":650,
                  "obstacle":false,
                  "id":"x0:y13"
               },
               {
                  "x":1,
                  "y":13,
                  "posX":50,
                  "posY":650,
                  "obstacle":false,
                  "id":"x1:y13"
               },
               {
                  "x":2,
                  "y":13,
                  "posX":100,
                  "posY":650,
                  "obstacle":false,
                  "id":"x2:y13"
               },
               {
                  "x":3,
                  "y":13,
                  "posX":150,
                  "posY":650,
                  "obstacle":false,
                  "id":"x3:y13"
               },
               {
                  "x":4,
                  "y":13,
                  "posX":200,
                  "posY":650,
                  "obstacle":false,
                  "id":"x4:y13"
               },
               {
                  "x":5,
                  "y":13,
                  "posX":250,
                  "posY":650,
                  "obstacle":false,
                  "id":"x5:y13"
               },
               {
                  "x":6,
                  "y":13,
                  "posX":300,
                  "posY":650,
                  "obstacle":false,
                  "id":"x6:y13"
               },
               {
                  "x":7,
                  "y":13,
                  "posX":350,
                  "posY":650,
                  "obstacle":false,
                  "id":"x7:y13"
               },
               {
                  "x":8,
                  "y":13,
                  "posX":400,
                  "posY":650,
                  "obstacle":false,
                  "id":"x8:y13"
               },
               {
                  "x":9,
                  "y":13,
                  "posX":450,
                  "posY":650,
                  "obstacle":false,
                  "id":"x9:y13"
               },
               {
                  "x":10,
                  "y":13,
                  "posX":500,
                  "posY":650,
                  "obstacle":false,
                  "id":"x10:y13"
               },
               {
                  "x":11,
                  "y":13,
                  "posX":550,
                  "posY":650,
                  "obstacle":false,
                  "id":"x11:y13"
               },
               {
                  "x":12,
                  "y":13,
                  "posX":600,
                  "posY":650,
                  "obstacle":false,
                  "id":"x12:y13"
               },
               {
                  "x":13,
                  "y":13,
                  "posX":650,
                  "posY":650,
                  "obstacle":false,
                  "id":"x13:y13"
               },
               {
                  "x":14,
                  "y":13,
                  "posX":700,
                  "posY":650,
                  "obstacle":false,
                  "id":"x14:y13"
               },
               {
                  "x":15,
                  "y":13,
                  "posX":750,
                  "posY":650,
                  "obstacle":false,
                  "id":"x15:y13"
               },
               {
                  "x":16,
                  "y":13,
                  "posX":800,
                  "posY":650,
                  "obstacle":false,
                  "id":"x16:y13"
               },
               {
                  "x":17,
                  "y":13,
                  "posX":850,
                  "posY":650,
                  "obstacle":false,
                  "id":"x17:y13"
               },
               {
                  "x":18,
                  "y":13,
                  "posX":900,
                  "posY":650,
                  "obstacle":false,
                  "id":"x18:y13"
               },
               {
                  "x":19,
                  "y":13,
                  "posX":950,
                  "posY":650,
                  "obstacle":false,
                  "id":"x19:y13"
               }
            ],
            [
               {
                  "x":0,
                  "y":14,
                  "posX":0,
                  "posY":700,
                  "obstacle":false,
                  "id":"x0:y14"
               },
               {
                  "x":1,
                  "y":14,
                  "posX":50,
                  "posY":700,
                  "obstacle":false,
                  "id":"x1:y14"
               },
               {
                  "x":2,
                  "y":14,
                  "posX":100,
                  "posY":700,
                  "obstacle":false,
                  "id":"x2:y14"
               },
               {
                  "x":3,
                  "y":14,
                  "posX":150,
                  "posY":700,
                  "obstacle":false,
                  "id":"x3:y14"
               },
               {
                  "x":4,
                  "y":14,
                  "posX":200,
                  "posY":700,
                  "obstacle":false,
                  "id":"x4:y14"
               },
               {
                  "x":5,
                  "y":14,
                  "posX":250,
                  "posY":700,
                  "obstacle":false,
                  "id":"x5:y14"
               },
               {
                  "x":6,
                  "y":14,
                  "posX":300,
                  "posY":700,
                  "obstacle":false,
                  "id":"x6:y14"
               },
               {
                  "x":7,
                  "y":14,
                  "posX":350,
                  "posY":700,
                  "obstacle":false,
                  "id":"x7:y14"
               },
               {
                  "x":8,
                  "y":14,
                  "posX":400,
                  "posY":700,
                  "obstacle":false,
                  "id":"x8:y14"
               },
               {
                  "x":9,
                  "y":14,
                  "posX":450,
                  "posY":700,
                  "obstacle":false,
                  "id":"x9:y14"
               },
               {
                  "x":10,
                  "y":14,
                  "posX":500,
                  "posY":700,
                  "obstacle":false,
                  "id":"x10:y14"
               },
               {
                  "x":11,
                  "y":14,
                  "posX":550,
                  "posY":700,
                  "obstacle":false,
                  "id":"x11:y14"
               },
               {
                  "x":12,
                  "y":14,
                  "posX":600,
                  "posY":700,
                  "obstacle":false,
                  "id":"x12:y14"
               },
               {
                  "x":13,
                  "y":14,
                  "posX":650,
                  "posY":700,
                  "obstacle":false,
                  "id":"x13:y14"
               },
               {
                  "x":14,
                  "y":14,
                  "posX":700,
                  "posY":700,
                  "obstacle":false,
                  "id":"x14:y14"
               },
               {
                  "x":15,
                  "y":14,
                  "posX":750,
                  "posY":700,
                  "obstacle":false,
                  "id":"x15:y14"
               },
               {
                  "x":16,
                  "y":14,
                  "posX":800,
                  "posY":700,
                  "obstacle":false,
                  "id":"x16:y14"
               },
               {
                  "x":17,
                  "y":14,
                  "posX":850,
                  "posY":700,
                  "obstacle":false,
                  "id":"x17:y14"
               },
               {
                  "x":18,
                  "y":14,
                  "posX":900,
                  "posY":700,
                  "obstacle":false,
                  "id":"x18:y14"
               },
               {
                  "x":19,
                  "y":14,
                  "posX":950,
                  "posY":700,
                  "obstacle":false,
                  "id":"x19:y14"
               }
            ],
            [
               {
                  "x":0,
                  "y":15,
                  "posX":0,
                  "posY":750,
                  "obstacle":false,
                  "id":"x0:y15"
               },
               {
                  "x":1,
                  "y":15,
                  "posX":50,
                  "posY":750,
                  "obstacle":false,
                  "id":"x1:y15"
               },
               {
                  "x":2,
                  "y":15,
                  "posX":100,
                  "posY":750,
                  "obstacle":false,
                  "id":"x2:y15"
               },
               {
                  "x":3,
                  "y":15,
                  "posX":150,
                  "posY":750,
                  "obstacle":false,
                  "id":"x3:y15"
               },
               {
                  "x":4,
                  "y":15,
                  "posX":200,
                  "posY":750,
                  "obstacle":false,
                  "id":"x4:y15"
               },
               {
                  "x":5,
                  "y":15,
                  "posX":250,
                  "posY":750,
                  "obstacle":false,
                  "id":"x5:y15"
               },
               {
                  "x":6,
                  "y":15,
                  "posX":300,
                  "posY":750,
                  "obstacle":false,
                  "id":"x6:y15"
               },
               {
                  "x":7,
                  "y":15,
                  "posX":350,
                  "posY":750,
                  "obstacle":false,
                  "id":"x7:y15"
               },
               {
                  "x":8,
                  "y":15,
                  "posX":400,
                  "posY":750,
                  "obstacle":false,
                  "id":"x8:y15"
               },
               {
                  "x":9,
                  "y":15,
                  "posX":450,
                  "posY":750,
                  "obstacle":false,
                  "id":"x9:y15"
               },
               {
                  "x":10,
                  "y":15,
                  "posX":500,
                  "posY":750,
                  "obstacle":false,
                  "id":"x10:y15"
               },
               {
                  "x":11,
                  "y":15,
                  "posX":550,
                  "posY":750,
                  "obstacle":false,
                  "id":"x11:y15"
               },
               {
                  "x":12,
                  "y":15,
                  "posX":600,
                  "posY":750,
                  "obstacle":false,
                  "id":"x12:y15"
               },
               {
                  "x":13,
                  "y":15,
                  "posX":650,
                  "posY":750,
                  "obstacle":false,
                  "id":"x13:y15"
               },
               {
                  "x":14,
                  "y":15,
                  "posX":700,
                  "posY":750,
                  "obstacle":false,
                  "id":"x14:y15"
               },
               {
                  "x":15,
                  "y":15,
                  "posX":750,
                  "posY":750,
                  "obstacle":false,
                  "id":"x15:y15"
               },
               {
                  "x":16,
                  "y":15,
                  "posX":800,
                  "posY":750,
                  "obstacle":false,
                  "id":"x16:y15"
               },
               {
                  "x":17,
                  "y":15,
                  "posX":850,
                  "posY":750,
                  "obstacle":false,
                  "id":"x17:y15"
               },
               {
                  "x":18,
                  "y":15,
                  "posX":900,
                  "posY":750,
                  "obstacle":false,
                  "id":"x18:y15"
               },
               {
                  "x":19,
                  "y":15,
                  "posX":950,
                  "posY":750,
                  "obstacle":false,
                  "id":"x19:y15"
               }
            ],
            [
               {
                  "x":0,
                  "y":16,
                  "posX":0,
                  "posY":800,
                  "obstacle":false,
                  "id":"x0:y16"
               },
               {
                  "x":1,
                  "y":16,
                  "posX":50,
                  "posY":800,
                  "obstacle":false,
                  "id":"x1:y16"
               },
               {
                  "x":2,
                  "y":16,
                  "posX":100,
                  "posY":800,
                  "obstacle":false,
                  "id":"x2:y16"
               },
               {
                  "x":3,
                  "y":16,
                  "posX":150,
                  "posY":800,
                  "obstacle":false,
                  "id":"x3:y16"
               },
               {
                  "x":4,
                  "y":16,
                  "posX":200,
                  "posY":800,
                  "obstacle":false,
                  "id":"x4:y16"
               },
               {
                  "x":5,
                  "y":16,
                  "posX":250,
                  "posY":800,
                  "obstacle":false,
                  "id":"x5:y16"
               },
               {
                  "x":6,
                  "y":16,
                  "posX":300,
                  "posY":800,
                  "obstacle":false,
                  "id":"x6:y16"
               },
               {
                  "x":7,
                  "y":16,
                  "posX":350,
                  "posY":800,
                  "obstacle":false,
                  "id":"x7:y16"
               },
               {
                  "x":8,
                  "y":16,
                  "posX":400,
                  "posY":800,
                  "obstacle":false,
                  "id":"x8:y16"
               },
               {
                  "x":9,
                  "y":16,
                  "posX":450,
                  "posY":800,
                  "obstacle":false,
                  "id":"x9:y16"
               },
               {
                  "x":10,
                  "y":16,
                  "posX":500,
                  "posY":800,
                  "obstacle":false,
                  "id":"x10:y16"
               },
               {
                  "x":11,
                  "y":16,
                  "posX":550,
                  "posY":800,
                  "obstacle":false,
                  "id":"x11:y16"
               },
               {
                  "x":12,
                  "y":16,
                  "posX":600,
                  "posY":800,
                  "obstacle":false,
                  "id":"x12:y16"
               },
               {
                  "x":13,
                  "y":16,
                  "posX":650,
                  "posY":800,
                  "obstacle":false,
                  "id":"x13:y16"
               },
               {
                  "x":14,
                  "y":16,
                  "posX":700,
                  "posY":800,
                  "obstacle":false,
                  "id":"x14:y16"
               },
               {
                  "x":15,
                  "y":16,
                  "posX":750,
                  "posY":800,
                  "obstacle":false,
                  "id":"x15:y16"
               },
               {
                  "x":16,
                  "y":16,
                  "posX":800,
                  "posY":800,
                  "obstacle":false,
                  "id":"x16:y16"
               },
               {
                  "x":17,
                  "y":16,
                  "posX":850,
                  "posY":800,
                  "obstacle":false,
                  "id":"x17:y16"
               },
               {
                  "x":18,
                  "y":16,
                  "posX":900,
                  "posY":800,
                  "obstacle":false,
                  "id":"x18:y16"
               },
               {
                  "x":19,
                  "y":16,
                  "posX":950,
                  "posY":800,
                  "obstacle":false,
                  "id":"x19:y16"
               }
            ],
            [
               {
                  "x":0,
                  "y":17,
                  "posX":0,
                  "posY":850,
                  "obstacle":false,
                  "id":"x0:y17"
               },
               {
                  "x":1,
                  "y":17,
                  "posX":50,
                  "posY":850,
                  "obstacle":false,
                  "id":"x1:y17"
               },
               {
                  "x":2,
                  "y":17,
                  "posX":100,
                  "posY":850,
                  "obstacle":false,
                  "id":"x2:y17"
               },
               {
                  "x":3,
                  "y":17,
                  "posX":150,
                  "posY":850,
                  "obstacle":false,
                  "id":"x3:y17"
               },
               {
                  "x":4,
                  "y":17,
                  "posX":200,
                  "posY":850,
                  "obstacle":false,
                  "id":"x4:y17"
               },
               {
                  "x":5,
                  "y":17,
                  "posX":250,
                  "posY":850,
                  "obstacle":false,
                  "id":"x5:y17"
               },
               {
                  "x":6,
                  "y":17,
                  "posX":300,
                  "posY":850,
                  "obstacle":false,
                  "id":"x6:y17"
               },
               {
                  "x":7,
                  "y":17,
                  "posX":350,
                  "posY":850,
                  "obstacle":false,
                  "id":"x7:y17"
               },
               {
                  "x":8,
                  "y":17,
                  "posX":400,
                  "posY":850,
                  "obstacle":false,
                  "id":"x8:y17"
               },
               {
                  "x":9,
                  "y":17,
                  "posX":450,
                  "posY":850,
                  "obstacle":false,
                  "id":"x9:y17"
               },
               {
                  "x":10,
                  "y":17,
                  "posX":500,
                  "posY":850,
                  "obstacle":false,
                  "id":"x10:y17"
               },
               {
                  "x":11,
                  "y":17,
                  "posX":550,
                  "posY":850,
                  "obstacle":false,
                  "id":"x11:y17"
               },
               {
                  "x":12,
                  "y":17,
                  "posX":600,
                  "posY":850,
                  "obstacle":false,
                  "id":"x12:y17"
               },
               {
                  "x":13,
                  "y":17,
                  "posX":650,
                  "posY":850,
                  "obstacle":false,
                  "id":"x13:y17"
               },
               {
                  "x":14,
                  "y":17,
                  "posX":700,
                  "posY":850,
                  "obstacle":false,
                  "id":"x14:y17"
               },
               {
                  "x":15,
                  "y":17,
                  "posX":750,
                  "posY":850,
                  "obstacle":false,
                  "id":"x15:y17"
               },
               {
                  "x":16,
                  "y":17,
                  "posX":800,
                  "posY":850,
                  "obstacle":false,
                  "id":"x16:y17"
               },
               {
                  "x":17,
                  "y":17,
                  "posX":850,
                  "posY":850,
                  "obstacle":false,
                  "id":"x17:y17"
               },
               {
                  "x":18,
                  "y":17,
                  "posX":900,
                  "posY":850,
                  "obstacle":false,
                  "id":"x18:y17"
               },
               {
                  "x":19,
                  "y":17,
                  "posX":950,
                  "posY":850,
                  "obstacle":false,
                  "id":"x19:y17"
               }
            ],
            [
               {
                  "x":0,
                  "y":18,
                  "posX":0,
                  "posY":900,
                  "obstacle":false,
                  "id":"x0:y18"
               },
               {
                  "x":1,
                  "y":18,
                  "posX":50,
                  "posY":900,
                  "obstacle":false,
                  "id":"x1:y18"
               },
               {
                  "x":2,
                  "y":18,
                  "posX":100,
                  "posY":900,
                  "obstacle":false,
                  "id":"x2:y18"
               },
               {
                  "x":3,
                  "y":18,
                  "posX":150,
                  "posY":900,
                  "obstacle":false,
                  "id":"x3:y18"
               },
               {
                  "x":4,
                  "y":18,
                  "posX":200,
                  "posY":900,
                  "obstacle":false,
                  "id":"x4:y18"
               },
               {
                  "x":5,
                  "y":18,
                  "posX":250,
                  "posY":900,
                  "obstacle":false,
                  "id":"x5:y18"
               },
               {
                  "x":6,
                  "y":18,
                  "posX":300,
                  "posY":900,
                  "obstacle":false,
                  "id":"x6:y18"
               },
               {
                  "x":7,
                  "y":18,
                  "posX":350,
                  "posY":900,
                  "obstacle":false,
                  "id":"x7:y18"
               },
               {
                  "x":8,
                  "y":18,
                  "posX":400,
                  "posY":900,
                  "obstacle":false,
                  "id":"x8:y18"
               },
               {
                  "x":9,
                  "y":18,
                  "posX":450,
                  "posY":900,
                  "obstacle":false,
                  "id":"x9:y18"
               },
               {
                  "x":10,
                  "y":18,
                  "posX":500,
                  "posY":900,
                  "obstacle":false,
                  "id":"x10:y18"
               },
               {
                  "x":11,
                  "y":18,
                  "posX":550,
                  "posY":900,
                  "obstacle":false,
                  "id":"x11:y18"
               },
               {
                  "x":12,
                  "y":18,
                  "posX":600,
                  "posY":900,
                  "obstacle":false,
                  "id":"x12:y18"
               },
               {
                  "x":13,
                  "y":18,
                  "posX":650,
                  "posY":900,
                  "obstacle":false,
                  "id":"x13:y18"
               },
               {
                  "x":14,
                  "y":18,
                  "posX":700,
                  "posY":900,
                  "obstacle":false,
                  "id":"x14:y18"
               },
               {
                  "x":15,
                  "y":18,
                  "posX":750,
                  "posY":900,
                  "obstacle":false,
                  "id":"x15:y18"
               },
               {
                  "x":16,
                  "y":18,
                  "posX":800,
                  "posY":900,
                  "obstacle":false,
                  "id":"x16:y18"
               },
               {
                  "x":17,
                  "y":18,
                  "posX":850,
                  "posY":900,
                  "obstacle":false,
                  "id":"x17:y18"
               },
               {
                  "x":18,
                  "y":18,
                  "posX":900,
                  "posY":900,
                  "obstacle":false,
                  "id":"x18:y18"
               },
               {
                  "x":19,
                  "y":18,
                  "posX":950,
                  "posY":900,
                  "obstacle":false,
                  "id":"x19:y18"
               }
            ],
            [
               {
                  "x":0,
                  "y":19,
                  "posX":0,
                  "posY":950,
                  "obstacle":false,
                  "id":"x0:y19"
               },
               {
                  "x":1,
                  "y":19,
                  "posX":50,
                  "posY":950,
                  "obstacle":false,
                  "id":"x1:y19"
               },
               {
                  "x":2,
                  "y":19,
                  "posX":100,
                  "posY":950,
                  "obstacle":false,
                  "id":"x2:y19"
               },
               {
                  "x":3,
                  "y":19,
                  "posX":150,
                  "posY":950,
                  "obstacle":false,
                  "id":"x3:y19"
               },
               {
                  "x":4,
                  "y":19,
                  "posX":200,
                  "posY":950,
                  "obstacle":false,
                  "id":"x4:y19"
               },
               {
                  "x":5,
                  "y":19,
                  "posX":250,
                  "posY":950,
                  "obstacle":false,
                  "id":"x5:y19"
               },
               {
                  "x":6,
                  "y":19,
                  "posX":300,
                  "posY":950,
                  "obstacle":false,
                  "id":"x6:y19"
               },
               {
                  "x":7,
                  "y":19,
                  "posX":350,
                  "posY":950,
                  "obstacle":false,
                  "id":"x7:y19"
               },
               {
                  "x":8,
                  "y":19,
                  "posX":400,
                  "posY":950,
                  "obstacle":false,
                  "id":"x8:y19"
               },
               {
                  "x":9,
                  "y":19,
                  "posX":450,
                  "posY":950,
                  "obstacle":false,
                  "id":"x9:y19"
               },
               {
                  "x":10,
                  "y":19,
                  "posX":500,
                  "posY":950,
                  "obstacle":false,
                  "id":"x10:y19"
               },
               {
                  "x":11,
                  "y":19,
                  "posX":550,
                  "posY":950,
                  "obstacle":false,
                  "id":"x11:y19"
               },
               {
                  "x":12,
                  "y":19,
                  "posX":600,
                  "posY":950,
                  "obstacle":false,
                  "id":"x12:y19"
               },
               {
                  "x":13,
                  "y":19,
                  "posX":650,
                  "posY":950,
                  "obstacle":false,
                  "id":"x13:y19"
               },
               {
                  "x":14,
                  "y":19,
                  "posX":700,
                  "posY":950,
                  "obstacle":false,
                  "id":"x14:y19"
               },
               {
                  "x":15,
                  "y":19,
                  "posX":750,
                  "posY":950,
                  "obstacle":false,
                  "id":"x15:y19"
               },
               {
                  "x":16,
                  "y":19,
                  "posX":800,
                  "posY":950,
                  "obstacle":false,
                  "id":"x16:y19"
               },
               {
                  "x":17,
                  "y":19,
                  "posX":850,
                  "posY":950,
                  "obstacle":false,
                  "id":"x17:y19"
               },
               {
                  "x":18,
                  "y":19,
                  "posX":900,
                  "posY":950,
                  "obstacle":false,
                  "id":"x18:y19"
               },
               {
                  "x":19,
                  "y":19,
                  "posX":950,
                  "posY":950,
                  "obstacle":false,
                  "id":"x19:y19"
               }
            ]
         ]

        
    }
]